#!/usr/bin/env python3
"""Build renamed OFL WOFF2 subsets from pinned Plangothic P1/P2 sources.
Usage: python scripts/build-rare-fonts.py /path/to/source-directory
Requires fonttools==4.60.2 brotli==1.1.0. No network access at build time.
"""
import hashlib
import json
from pathlib import Path
import sys
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'public/fonts/rare-han'
EXPECTED_HASHES = {
    'SourceHanSansSC-Regular.otf': 'f1d8611151880c6c336aabeac4640ef434fa13cbfbf1ffe82d0a71b2a5637256',
    'PlangothicP1-Regular.ttf': '550b5d0775b15405946b18f4843df439a51e69508d7e6778d94c1f7a53dc5ad6',
    'PlangothicP2-Regular.ttf': '681933370adfe0fc7253f77735275a82fea09fe4f8adba907bdeb46c110daf8f',
}
RANGES = [(0x3400, 0x4DBF), (0xF900, 0xFAFF), (0x20000, 0x2EE5F), (0x2F800, 0x2FA1F), (0x30000, 0x3347F)]


def unicode_ranges(points):
    result = []
    start = end = points[0]
    for cp in points[1:]:
        if cp == end + 1:
            end = cp
        else:
            result.append(f'U+{start:X}' if start == end else f'U+{start:X}-{end:X}')
            start = end = cp
    result.append(f'U+{start:X}' if start == end else f'U+{start:X}-{end:X}')
    return ','.join(result)


def main():
    source = Path(sys.argv[1])
    OUT.mkdir(parents=True, exist_ok=True)
    faces, manifest, covered = [], [], set()
    source_hashes = {}
    for filename in ('SourceHanSansSC-Regular.otf', 'PlangothicP1-Regular.ttf', 'PlangothicP2-Regular.ttf'):
        path = source / filename
        source_hashes[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
        if source_hashes[path.name] != EXPECTED_HASHES[path.name]:
            raise ValueError(f'Unexpected source checksum: {path.name}')
        font = TTFont(path)
        cps = sorted(cp for cp in font.getBestCmap() if any(a <= cp <= b for a, b in RANGES) and cp not in covered)
        font.close()
        buckets = {}
        for cp in cps:
            buckets.setdefault(cp // 512, []).append(cp)
        for bucket, points in buckets.items():
            font = TTFont(path, recalcTimestamp=False)
            options = subset.Options()
            options.flavor = 'woff2'
            options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
            options.name_legacy = True
            options.name_languages = ['*']
            options.layout_features = []
            options.hinting = False
            sub = subset.Subsetter(options=options)
            sub.populate(unicodes=points)
            sub.subset(font)
            # Subsetting is a modification: do not retain OFL reserved names.
            names = {1: 'Fangji Rare Han', 2: 'Regular', 3: f'FangjiRareHan-{bucket:X}', 4: 'Fangji Rare Han Regular', 6: f'FangjiRareHan-{bucket:X}', 16: 'Fangji Rare Han', 17: 'Regular'}
            for record in list(font['name'].names):
                if record.nameID in names:
                    font['name'].setName(names[record.nameID], record.nameID, record.platformID, record.platEncID, record.langID)
            if 'CFF ' in font:
                cff = font['CFF '].cff
                cff.fontNames = [names[6]]
                cff.topDictIndex[0].FamilyName = names[1]
                cff.topDictIndex[0].FullName = names[4]
            font.flavor = 'woff2'
            temp = OUT / 'subset.tmp'
            font.save(temp)
            font.close()
            data = temp.read_bytes()
            name = f'rare-{bucket*512:x}-{hashlib.sha256(data).hexdigest()[:12]}.woff2'
            temp.rename(OUT / name)
            # Verify serialized output, not just the input font's declared coverage.
            output = TTFont(OUT / name)
            actual = set(output.getBestCmap())
            assert actual == set(points), name
            assert all(output.getBestCmap()[cp] != '.notdef' for cp in points), name
            output.close()
            covered.update(points)
            ranges = unicode_ranges(points)
            faces.append(f'@font-face {{\n  font-family: "Fangji Rare Han";\n  src: url("/fonts/rare-han/{name}") format("woff2");\n  font-style: normal;\n  font-weight: 400;\n  font-display: swap;\n  unicode-range: {ranges};\n}}')
            manifest.append({'file': name, 'bytes': len(data), 'unicodeRange': ranges, 'codepoints': len(points)})
    assert all(ord(char) in covered for char in '𢶀𠮷㙟𰻞䲠')
    (ROOT / 'src/rare-fonts.css').write_text('/* Generated by scripts/build-rare-fonts.py; OFL license in /fonts/rare-han/OFL.txt. */\n' + '\n\n'.join(faces) + '\n')
    (OUT / 'manifest.json').write_text(json.dumps({'upstream': 'Source Han Sans 2.005R + Plangothic V2.9.5795', 'sources': source_hashes, 'glyphs': len(covered), 'subsets': manifest}, indent=2) + '\n')
    (OUT / 'OFL.txt').write_bytes((source / 'OFL.txt').read_bytes())
    (OUT / 'SourceHanSans-OFL.txt').write_bytes((source / 'SourceHanSans-OFL.txt').read_bytes())
    keep = {item['file'] for item in manifest}
    for old in OUT.glob('rare-*.woff2'):
        if old.name not in keep:
            old.unlink()
    print(f'{len(manifest)} subsets, {len(covered)} code points, {sum(x["bytes"] for x in manifest)} bytes')

if __name__ == '__main__':
    main()
