const {chromium}=require('playwright');
(async()=>{
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL || 'chrome'});const page=await browser.newPage();page.on('dialog', dialog=>dialog.accept()); const errors=[];page.on('pageerror',e=>errors.push(e.message));
const row={'字词':'测试','读音':'tɛ','释义':'演示材料'};const record={id:'page1',project:'project1',page_number:1,pdf_page:1,ocr_row_json:JSON.stringify(row),expand:{project:{name:'虚构测试项目'},project_file:{id:'file1',collectionId:'project_files',file:'fixture.pdf'}}};
await page.route('**/api/**',async route=>{const url=route.request().url();if(url.includes('/api/files/')) return route.fulfill({contentType:'application/pdf',body:Buffer.from('JVBERi0xLjMKJZOMi54gUmVwb3J0TGFiIEdlbmVyYXRlZCBQREYgZG9jdW1lbnQgKG9wZW5zb3VyY2UpCjEgMCBvYmoKPDwKL0YxIDIgMCBSCj4+CmVuZG9iagoyIDAgb2JqCjw8Ci9CYXNlRm9udCAvSGVsdmV0aWNhIC9FbmNvZGluZyAvV2luQW5zaUVuY29kaW5nIC9OYW1lIC9GMSAvU3VidHlwZSAvVHlwZTEgL1R5cGUgL0ZvbnQKPj4KZW5kb2JqCjMgMCBvYmoKPDwKL0NvbnRlbnRzIDcgMCBSIC9NZWRpYUJveCBbIDAgMCA1OTUuMjc1NiA4NDEuODg5OCBdIC9QYXJlbnQgNiAwIFIgL1Jlc291cmNlcyA8PAovRm9udCAxIDAgUiAvUHJvY1NldCBbIC9QREYgL1RleHQgL0ltYWdlQiAvSW1hZ2VDIC9JbWFnZUkgXQo+PiAvUm90YXRlIDAgL1RyYW5zIDw8Cgo+PiAKICAvVHlwZSAvUGFnZQo+PgplbmRvYmoKNCAwIG9iago8PAovUGFnZU1vZGUgL1VzZU5vbmUgL1BhZ2VzIDYgMCBSIC9UeXBlIC9DYXRhbG9nCj4+CmVuZG9iago1IDAgb2JqCjw8Ci9BdXRob3IgKGFub255bW91cykgL0NyZWF0aW9uRGF0ZSAoRDoyMDI2MDkwOTAyMzUyNSswOCcwMCcpIC9DcmVhdG9yIChhbm9ueW1vdXMpIC9LZXl3b3JkcyAoKSAvTW9kRGF0ZSAoRDoyMDI2MDkwOTAyMzUyNSswOCcwMCcpIC9Qcm9kdWNlciAoUmVwb3J0TGFiIFBERiBMaWJyYXJ5IC0gXChvcGVuc291cmNlXCkpIAogIC9TdWJqZWN0ICh1bnNwZWNpZmllZCkgL1RpdGxlICh1bnRpdGxlZCkgL1RyYXBwZWQgL0ZhbHNlCj4+CmVuZG9iago2IDAgb2JqCjw8Ci9Db3VudCAxIC9LaWRzIFsgMyAwIFIgXSAvVHlwZSAvUGFnZXMKPj4KZW5kb2JqCjcgMCBvYmoKPDwKL0ZpbHRlciBbIC9BU0NJSTg1RGVjb2RlIC9GbGF0ZURlY29kZSBdIC9MZW5ndGggMTg2Cj4+CnN0cmVhbQpHYXJXMFltUz81JjRIRENgS1ksImo/Y1xJJ1hTSlVmY1EkbFQhIkdiPVlFOEVoRiZxSEE3ND0pX2ZOblNcOUhPVllUZFRzIz9RRjw+YV5uTi9fNi1wXURHcFgqL2YoUEMsK0U1Pys+WlY4KmwyJGtnXlNeXD0vLillNUFgXzBRPXA5SnJEQWVTTydTSGBvOkxgImlmciooO1YwSic0KS1NKm90MjU8UDxEJjgzIUoyK3NcaGE9WjUxfj5lbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA4CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDA2MSAwMDAwMCBuIAowMDAwMDAwMDkyIDAwMDAwIG4gCjAwMDAwMDAxOTkgMDAwMDAgbiAKMDAwMDAwMDQwMiAwMDAwMCBuIAowMDAwMDAwNDcwIDAwMDAwIG4gCjAwMDAwMDA3MzEgMDAwMDAgbiAKMDAwMDAwMDc5MCAwMDAwMCBuIAp0cmFpbGVyCjw8Ci9JRCAKWzwxNDdmNjJkZDU0NjExMzQxZjk4ODUwZDZmNzQ1Y2Y1MD48MTQ3ZjYyZGQ1NDYxMTM0MWY5ODg1MGQ2Zjc0NWNmNTA+XQolIFJlcG9ydExhYiBnZW5lcmF0ZWQgUERGIGRvY3VtZW50IC0tIGRpZ2VzdCAob3BlbnNvdXJjZSkKCi9JbmZvIDUgMCBSCi9Sb290IDQgMCBSCi9TaXplIDgKPj4Kc3RhcnR4cmVmCjEwNjYKJSVFT0YK', 'base64')});let data={items:[],totalItems:0,totalPages:1,page:1,perPage:100};
if(url.endsWith('/task'))data=record;
if(url.endsWith('/claim'))data={...record,leaseToken:'fixture-lease',leaseExpiresAt:'2099-01-01T00:00:00Z'};
if(url.endsWith('/mine'))data=[record];
if(url.endsWith('/keyboards'))data={items:[{keyboardId:'ipa',name:'音标键盘',definition:{sections:[{id:'vowels',label:'元音',defaultOpen:true,keys:['ɑ','ɛ','ə','ɔ'].map(value=>({value}))},{id:'tones',label:'声调',keys:[{value:'˥'}]}]}}],defaultKeyboardId:'ipa'};
if(url.endsWith('/arbitration'))data={page:record,attempts:[{id:'a',pass_no:1,row_json:JSON.stringify(row)},{id:'b',pass_no:2,row_json:JSON.stringify({...row,读音:'ta'})}]};
await route.fulfill({json:data});});
for(const admin of [false,true]){
await page.setViewportSize({width:1440,height:900});await page.goto('http://localhost:5173/tests/fixtures/review.html'+(admin?'?admin':''));await page.waitForTimeout(1000); await page.locator('.ipa-key').first().waitFor({timeout:3000});
const source=await page.locator('.source-panel').boundingBox(),key=await page.locator('.keyboard-panel').boundingBox(),fields=await page.locator('.fields-panel').boundingBox();if(!(key.x<fields.x && key.y>source.y))throw Error('Desktop placement');
await page.screenshot({path:`/tmp/review-${admin?'arb':'proof'}-desktop.png`});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(150); await page.screenshot({path:`/tmp/review-${admin?'arb':'proof'}-mobile-pdf.png`});
await page.getByRole('button',{name:'字符键盘',exact:true}).click();await page.getByRole('button',{name:'钉住',exact:true}).click();
await page.getByRole('button',{name:'声调 1',exact:true}).click(); if(!await page.getByRole('button',{name:'插入字符 ˥',exact:true}).isVisible())throw Error('Group switch failed'); await page.getByRole('button',{name:'元音 4',exact:true}).click(); await page.locator('.ipa-key').first().click();
if(!await page.locator('textarea:visible').first().inputValue().then(v=>v.includes('ɑ')))throw Error('Insertion failed');
await page.screenshot({path:`/tmp/review-${admin?'arb':'proof'}-mobile.png`});
if(!admin){await page.getByRole('button',{name:'下一个',exact:true}).click();if(await page.locator('.proofread-field:visible').count()!==1)throw Error('Field navigation');await page.getByRole('button',{name:'下一个',exact:true}).click();await page.getByRole('button',{name:'整条总览',exact:true}).click();if(await page.locator('.proofread-field:visible').count()!==3)throw Error('Overview');if(await page.locator('.ipa-key').first().isVisible())throw Error('Overview keyboard not hidden');}
}
if(errors.length)throw Error(errors.join('\n'));console.log('Desktop placement, mobile insertion, pinned keyboard, navigation and overview passed for mocked pages.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
